'use client';

// ── NFL Elo — weekly dashboard ───────────────────────────────────────────────
// Two data paths meet on this page, and keeping them separate is the whole
// design:
//
//   Ratings and win probabilities  → /data/nfl-elo/season.json, regenerated by
//     scripts/build-nfl-elo.ts. Slow-moving and expensive, so it is computed
//     ahead of time and served as a static file. Probabilities are frozen at
//     kickoff on purpose — this is the model's pre-game view, not a live one.
//
//   Scores                         → ESPN's public scoreboard, fetched in the
//     reader's browser and refreshed each minute. Fast-moving and cheap.
//
// Nothing is proxied through a server, so the site stays fully static.

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import Footer from '@/components/Footer';
import { TEAMS, resolveTeam, fullName, shortName } from './teams';
import type { EloSeason, GameProjection, QbRating, TeamRating } from './engine';

const DATA_URL = '/data/nfl-elo/season.json';
const ESPN_SCOREBOARD = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard';
const REFRESH_MS = 60_000;

/** Two tiles replace the game list with a ranked table instead of filtering it. */
const QB_VIEW = 'QB_VIEW';
const ELO_VIEW = 'ELO_VIEW';

/** How many weeks to render before the reader scrolls for more. */
const INITIAL_WEEKS = 2;

interface LiveScore {
  away: number | null;
  home: number | null;
  state: 'pre' | 'in' | 'post';
  detail: string;
}

/* eslint-disable @typescript-eslint/no-explicit-any */

/** Key a game by its two teams, which is stable across both feeds. */
function matchupKey(away: string, home: string): string {
  return `${away}@${home}`;
}

function parseScoreboard(payload: any): Map<string, LiveScore> {
  const out = new Map<string, LiveScore>();
  for (const event of payload?.events ?? []) {
    const comp = event?.competitions?.[0];
    if (!comp) continue;
    const home = comp.competitors?.find((c: any) => c.homeAway === 'home');
    const away = comp.competitors?.find((c: any) => c.homeAway === 'away');
    if (!home || !away) continue;
    const homeAbbr = resolveTeam(home.team?.abbreviation ?? '')?.abbr;
    const awayAbbr = resolveTeam(away.team?.abbreviation ?? '')?.abbr;
    if (!homeAbbr || !awayAbbr) continue;
    const toScore = (raw: unknown) => {
      const n = Number(raw);
      return Number.isFinite(n) ? n : null;
    };
    out.set(matchupKey(awayAbbr, homeAbbr), {
      away: toScore(away.score),
      home: toScore(home.score),
      state: (comp.status?.type?.state ?? 'pre') as LiveScore['state'],
      detail: comp.status?.type?.shortDetail ?? '',
    });
  }
  return out;
}

/** YYYYMMDD, as ESPN's scoreboard wants its date range. */
function espnDate(d: Date): string {
  return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, '0')}${String(d.getUTCDate()).padStart(2, '0')}`;
}

function formatKickoff(iso: string | null, gameday: string): string {
  if (!iso) return gameday;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return gameday;
  return d.toLocaleString(undefined, {
    weekday: 'short', month: 'short', day: 'numeric',
    hour: 'numeric', minute: '2-digit',
  });
}

function pct(p: number): string {
  return `${(p * 100).toFixed(0)}%`;
}

/** "IND -2.2" — the model's line, quoted on whichever side is favoured. */
function spreadLabel(game: GameProjection): string {
  if (Math.abs(game.spread) < 0.05) return 'Pick ’em';
  const favourite = game.spread < 0 ? game.home : game.away;
  return `${favourite} −${Math.abs(game.spread).toFixed(1)}`;
}

export default function NflEloPage() {
  const [data, setData] = useState<EloSeason | null>(null);
  const [live, setLive] = useState<Map<string, LiveScore>>(new Map());
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [activeWeek, setActiveWeek] = useState<number | null>(null);

  // Only a slice of the season is mounted at a time; the rest arrives as the
  // reader scrolls. 272 game cards is a lot of DOM to build up front.
  const [weekRange, setWeekRange] = useState<{ min: number; max: number } | null>(null);
  const [pendingScroll, setPendingScroll] = useState<number | null>(null);

  const weekRefs = useRef<Map<number, HTMLElement>>(new Map());
  const sentinelRef = useRef<HTMLDivElement | null>(null);
  const railRef = useRef<HTMLDivElement | null>(null);

  // ── static model data ──────────────────────────────────────────────────────
  useEffect(() => {
    let cancelled = false;
    fetch(DATA_URL, { cache: 'no-store' })
      .then((r) => {
        if (!r.ok) throw new Error(`ratings unavailable (${r.status})`);
        return r.json();
      })
      .then((json: EloSeason) => { if (!cancelled) setData(json); })
      .catch((e: Error) => { if (!cancelled) setError(e.message); });
    return () => { cancelled = true; };
  }, []);

  // ── live scores, refreshed on a timer ──────────────────────────────────────
  const loadScores = useCallback(async () => {
    const now = new Date();
    const from = new Date(now.getTime() - 6 * 86400000);
    const to = new Date(now.getTime() + 6 * 86400000);
    try {
      const res = await fetch(
        `${ESPN_SCOREBOARD}?dates=${espnDate(from)}-${espnDate(to)}&limit=400`,
        { cache: 'no-store' },
      );
      if (!res.ok) return;
      setLive(parseScoreboard(await res.json()));
    } catch {
      // A scoreboard outage must not take the projections down with it.
    }
  }, []);

  useEffect(() => {
    loadScores();
    const id = setInterval(loadScores, REFRESH_MS);
    return () => clearInterval(id);
  }, [loadScores]);

  // ── derived views ──────────────────────────────────────────────────────────
  const showingQbs = selected === QB_VIEW;
  const showingElo = selected === ELO_VIEW;
  const showingTable = showingQbs || showingElo;

  const games = useMemo(() => {
    if (!data) return [];
    const filtered = selected && !showingQbs && !showingElo
      ? data.games.filter((g) => g.home === selected || g.away === selected)
      : data.games;
    return [...filtered].sort((a, b) => {
      const ak = a.kickoff ?? `${a.gameday}T00:00:00Z`;
      const bk = b.kickoff ?? `${b.gameday}T00:00:00Z`;
      return ak < bk ? -1 : ak > bk ? 1 : a.gameId < b.gameId ? -1 : 1;
    });
  }, [data, selected, showingQbs, showingElo]);

  const weeks = useMemo(() => {
    const byWeek = new Map<number, GameProjection[]>();
    for (const g of games) {
      if (!byWeek.has(g.week)) byWeek.set(g.week, []);
      byWeek.get(g.week)!.push(g);
    }
    return [...byWeek.entries()].sort((a, b) => a[0] - b[0]);
  }, [games]);

  /** The week the season is actually on: the first with a game not yet final. */
  const currentWeek = useMemo(() => {
    if (!data) return null;
    const now = Date.now();
    const upcoming = [...data.games]
      .filter((g) => g.homeScore === null)
      .sort((a, b) => (a.kickoff ?? '') < (b.kickoff ?? '') ? -1 : 1);
    const next = upcoming.find((g) => !g.kickoff || new Date(g.kickoff).getTime() > now - 4 * 3600000);
    return next?.week ?? (upcoming[0]?.week ?? null);
  }, [data]);

  // Open on the week the season is on rather than Week 1 in September, and
  // mount only that week plus the next. Starting the window here beats scrolling
  // to it: no jump, and the filters stay where the reader left them.
  useEffect(() => {
    if (weeks.length === 0) { setWeekRange(null); return; }
    const numbers = weeks.map(([week]) => week);
    const startAt = currentWeek === null ? 0 : Math.max(0, numbers.indexOf(currentWeek));
    setWeekRange({
      min: numbers[startAt],
      max: numbers[Math.min(startAt + INITIAL_WEEKS - 1, numbers.length - 1)],
    });
    setActiveWeek(numbers[startAt]);
  }, [weeks, currentWeek]);

  const visibleWeeks = useMemo(
    () => (weekRange ? weeks.filter(([week]) => week >= weekRange.min && week <= weekRange.max) : []),
    [weeks, weekRange],
  );

  const earlierWeeks = weekRange ? weeks.filter(([week]) => week < weekRange.min).length : 0;
  const laterWeeks = weekRange ? weeks.filter(([week]) => week > weekRange.max).length : 0;

  const showMore = useCallback((direction: 'earlier' | 'later') => {
    setWeekRange((range) => {
      if (!range) return range;
      if (direction === 'later') {
        const next = weeks.find(([week]) => week > range.max);
        return next ? { ...range, max: next[0] } : range;
      }
      const previous = [...weeks].reverse().find(([week]) => week < range.min);
      return previous ? { ...range, min: previous[0] } : range;
    });
  }, [weeks]);

  // Pull in the next week as the reader approaches the end of what is mounted.
  useEffect(() => {
    if (showingTable || laterWeeks === 0) return;
    const el = sentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      (entries) => { if (entries.some((e) => e.isIntersecting)) showMore('later'); },
      { rootMargin: '600px 0px' },
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [showingTable, laterWeeks, showMore]);

  // A rail click may target a week that is not mounted yet, so the scroll waits
  // for the render that brings it in.
  useEffect(() => {
    if (pendingScroll === null) return;
    const el = weekRefs.current.get(pendingScroll);
    if (!el) return;
    window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 90, behavior: 'smooth' });
    setPendingScroll(null);
  }, [pendingScroll, visibleWeeks]);

  // Scroll spy so the week rail tracks whatever is on screen.
  useEffect(() => {
    if (showingTable || visibleWeeks.length === 0) return;
    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top)[0];
        if (visible) {
          const week = Number((visible.target as HTMLElement).dataset.week);
          if (!Number.isNaN(week)) setActiveWeek(week);
        }
      },
      { rootMargin: '-100px 0px -60% 0px', threshold: 0 },
    );
    for (const el of weekRefs.current.values()) observer.observe(el);
    return () => observer.disconnect();
  }, [visibleWeeks, showingTable]);

  const jumpToWeek = (week: number) => {
    setWeekRange((range) => (range
      ? { min: Math.min(range.min, week), max: Math.max(range.max, week) }
      : { min: week, max: week }));
    setPendingScroll(week);
  };

  // On mobile the rail is a horizontal strip, so the active week can sit off
  // screen. Nudge it back into view by setting scrollLeft directly —
  // scrollIntoView would drag the whole page with it.
  useEffect(() => {
    const rail = railRef.current;
    if (!rail || activeWeek === null) return;
    if (rail.scrollWidth <= rail.clientWidth) return;
    const chip = rail.querySelector<HTMLElement>(`[data-week-link="${activeWeek}"]`);
    if (!chip) return;
    rail.scrollTo({
      left: chip.offsetLeft - rail.clientWidth / 2 + chip.offsetWidth / 2,
      behavior: 'smooth',
    });
  }, [activeWeek]);

  const registerWeek = (week: number) => (el: HTMLElement | null) => {
    if (el) weekRefs.current.set(week, el);
    else weekRefs.current.delete(week);
  };

  // ── render ─────────────────────────────────────────────────────────────────
  const eloByTeam = useMemo(() => {
    const m = new Map<string, { elo: number; rank: number; wins: number; losses: number; ties: number }>();
    for (const t of data?.teams ?? []) {
      m.set(t.team, { elo: t.elo, rank: t.rank, wins: t.wins, losses: t.losses, ties: t.ties });
    }
    return m;
  }, [data]);

  return (
    <main>
      <div className="page-bg" />

      <div className="container nfl-root">
        <div className="page-header">
          <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
            <Link href="/projects" style={{ color: 'var(--accent-secondary)' }}>Projects</Link>
            {' / '}NFL Elo Ratings
          </p>
          <h1 className="section-title"><span className="gradient-text">NFL Elo Ratings</span></h1>
          <p className="section-subtitle" style={{ marginBottom: 0 }}>
            A continuation of FiveThirtyEight&apos;s retired NFL Elo model, rebuilt from their
            published source and re-fit on modern seasons. Every team carries one rating; each
            matchup adds home field, rest and an adjustment for the starting quarterback. Scores
            update live &mdash; win probabilities are the model&apos;s pre-game view and stay fixed
            once a game kicks off.
          </p>
        </div>

        {error && (
          <div className="nfl-error">
            Couldn&apos;t load the ratings ({error}). The projections are generated ahead of time,
            so this is usually temporary.
          </div>
        )}

        {!data && !error && <div className="nfl-loading">Loading ratings&hellip;</div>}

        {data && (
          <>
            {/* ── team filter ── */}
            <div className="nfl-filter">
              <button
                type="button"
                className={`nfl-chip nfl-chip-all ${selected === null ? 'active' : ''}`}
                onClick={() => setSelected(null)}
              >
                All Games
              </button>

              {TEAMS.map((t) => {
                const rating = eloByTeam.get(t.abbr);
                return (
                  <button
                    key={t.abbr}
                    type="button"
                    title={`${fullName(t.abbr)}${rating ? ` — ${rating.elo} Elo, #${rating.rank}` : ''}`}
                    className={`nfl-chip ${selected === t.abbr ? 'active' : ''}`}
                    style={{ '--chip-color': t.color } as React.CSSProperties}
                    onClick={() => setSelected(selected === t.abbr ? null : t.abbr)}
                  >
                    <span className="nfl-chip-abbr">{t.abbr}</span>
                    {rating && <span className="nfl-chip-elo">{Math.round(rating.elo)}</span>}
                  </button>
                );
              })}

              <button
                type="button"
                className={`nfl-chip nfl-chip-qb ${showingQbs ? 'active' : ''}`}
                onClick={() => setSelected(showingQbs ? null : QB_VIEW)}
              >
                QBs
              </button>

              <button
                type="button"
                className={`nfl-chip nfl-chip-ratings ${showingElo ? 'active' : ''}`}
                onClick={() => setSelected(showingElo ? null : ELO_VIEW)}
              >
                Elo
              </button>
            </div>

            {showingQbs ? (
              <QbTable quarterbacks={data.quarterbacks} />
            ) : showingElo ? (
              <EloTable teams={data.teams} throughWeek={data.throughWeek} />
            ) : (
              <div className="nfl-layout">
                {/* ── week rail ── */}
                <aside className="nfl-weeks">
                  <div className="nfl-weeks-title">Weeks</div>
                  <div className="nfl-weeks-list" ref={railRef}>
                    {weeks.map(([week, list]) => (
                      <button
                        key={week}
                        type="button"
                        data-week-link={week}
                        className={`nfl-week-link ${activeWeek === week ? 'active' : ''} ${currentWeek === week ? 'now' : ''}`}
                        onClick={() => jumpToWeek(week)}
                      >
                        <span>Week {week}</span>
                        <span className="nfl-week-count">{list.length}</span>
                      </button>
                    ))}
                  </div>
                  {selected && (
                    <p className="nfl-weeks-note">
                      Showing {shortName(selected)} only.
                      {weeks.length < 18 && ' Missing weeks are the bye.'}
                    </p>
                  )}
                </aside>

                {/* ── games ── */}
                <div className="nfl-games">
                  {weeks.length === 0 && (
                    <div className="nfl-empty">No games to show.</div>
                  )}

                  {earlierWeeks > 0 && (
                    <button type="button" className="nfl-more" onClick={() => showMore('earlier')}>
                      Show earlier weeks ({earlierWeeks} before this)
                    </button>
                  )}

                  {visibleWeeks.map(([week, list]) => (
                    <section
                      key={week}
                      data-week={week}
                      ref={registerWeek(week)}
                      className="nfl-week-section"
                    >
                      <h2 className="nfl-week-heading">
                        Week {week}
                        {currentWeek === week && <span className="nfl-now-badge">This week</span>}
                      </h2>
                      {list.map((g) => (
                        <GameCard key={g.gameId} game={g} live={live.get(matchupKey(g.away, g.home))} />
                      ))}
                    </section>
                  ))}

                  {laterWeeks > 0 && (
                    <div ref={sentinelRef} className="nfl-sentinel">
                      <button type="button" className="nfl-more" onClick={() => showMore('later')}>
                        Show more weeks ({laterWeeks} {laterWeeks === 1 ? 'week' : 'weeks'} remaining)
                      </button>
                    </div>
                  )}
                </div>
              </div>
            )}

            <ModelNotes data={data} />
          </>
        )}
      </div>

      <style>{NFL_CSS}</style>
      <Footer />
    </main>
  );
}

// ── game card ────────────────────────────────────────────────────────────────

function GameCard({ game, live }: { game: GameProjection; live: LiveScore | undefined }) {
  const homeTeam = resolveTeam(game.home);
  const awayTeam = resolveTeam(game.away);

  // The generated file carries finished scores; ESPN carries whatever is in
  // progress. Prefer the live feed when it has something to say.
  const liveActive = live && (live.state === 'in' || live.state === 'post');
  const awayScore = liveActive && live.away !== null ? live.away : game.awayScore;
  const homeScore = liveActive && live.home !== null ? live.home : game.homeScore;
  const hasScore = awayScore !== null && homeScore !== null;

  const status = live?.state === 'in'
    ? { label: live.detail || 'Live', className: 'live' }
    : hasScore
      ? { label: 'Final', className: 'final' }
      : { label: formatKickoff(game.kickoff, game.gameday), className: 'scheduled' };

  const homeProb = game.homeWinProb;
  const awayProb = 1 - homeProb;
  const winner = hasScore
    ? (homeScore! > awayScore! ? game.home : homeScore! < awayScore! ? game.away : null)
    : null;

  return (
    <article className="nfl-game">
      <div className="nfl-game-top">
        <span className={`nfl-status nfl-status-${status.className}`}>{status.label}</span>
        <span className="nfl-venue">
          {game.neutralSite && 'Neutral · '}
          {game.stadium ?? ''}
        </span>
      </div>

      {[
        { abbr: game.away, team: awayTeam, qb: game.awayQb, score: awayScore, prob: awayProb, adj: game.awayQbAdj },
        { abbr: game.home, team: homeTeam, qb: game.homeQb, score: homeScore, prob: homeProb, adj: game.homeQbAdj },
      ].map((side) => (
        <div
          key={side.abbr}
          className={`nfl-side ${winner === side.abbr ? 'winner' : ''} ${winner && winner !== side.abbr ? 'loser' : ''}`}
        >
          <span className="nfl-side-bar" style={{ background: side.team?.color ?? 'var(--border)' }} />
          <span className="nfl-side-name">
            <span className="nfl-side-abbr">{side.abbr}</span>
            <span className="nfl-side-full">{side.team ? side.team.nickname : side.abbr}</span>
          </span>
          <span
            className="nfl-side-qb"
            title={side.adj === 0
              ? 'Exactly this team\u2019s expected starter \u2014 no rating adjustment'
              : `${side.adj > 0 ? '+' : ''}${side.adj} Elo vs this team\u2019s usual starter`}
          >
            {side.qb ?? '—'}
            {side.qb && (
              <em className={side.adj > 0 ? 'up' : side.adj < 0 ? 'down' : 'flat'}>
                {side.adj > 0 ? '+' : ''}{side.adj}
              </em>
            )}
          </span>
          <span className="nfl-side-score">{side.score ?? ''}</span>
          <span className="nfl-side-prob">{pct(side.prob)}</span>
        </div>
      ))}

      <div className="nfl-bar" aria-hidden="true">
        <span
          className="nfl-bar-away"
          style={{ width: `${awayProb * 100}%`, background: awayTeam?.color ?? '#999' }}
        />
        <span
          className="nfl-bar-home"
          style={{ width: `${homeProb * 100}%`, background: homeTeam?.color ?? '#555' }}
        />
      </div>

      <div className="nfl-game-foot">
        <span>Model line <strong>{spreadLabel(game)}</strong></span>
        <span>
          {game.projectedStarters ? 'Projected starters' : 'Announced starters'}
          {' · pre-game probability'}
        </span>
      </div>
    </article>
  );
}

// ── team rating table ────────────────────────────────────────────────────────

function EloTable({ teams, throughWeek }: { teams: TeamRating[]; throughWeek: number }) {
  const preseason = throughWeek === 0;
  return (
    <div className="nfl-qb-wrap">
      <p className="nfl-qb-intro">
        Every team&apos;s current rating, strongest first. The league mean is 1505, and a
        400-point gap is about 10-to-1 odds — so roughly every 25 points is a point of
        point spread. <strong>Preseason</strong> is where the team started the year after
        reverting a third of the way to the mean; <strong>Change</strong> is what the season
        has done to it since.
        {preseason && ' The season has not started, so every team still sits at its preseason mark.'}
      </p>
      <div className="nfl-table-scroll">
        <table className="nfl-qb-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Team</th>
              <th>Division</th>
              <th className="num">Elo</th>
              <th className="num">Preseason</th>
              <th className="num">Change</th>
              <th className="num">Record</th>
            </tr>
          </thead>
          <tbody>
            {teams.map((t) => {
              const team = resolveTeam(t.team);
              const change = Math.round(t.elo - t.eloPreseason);
              const record = t.ties > 0
                ? `${t.wins}-${t.losses}-${t.ties}`
                : `${t.wins}-${t.losses}`;
              return (
                <tr key={t.team}>
                  <td className="nfl-qb-rank">{t.rank}</td>
                  <td className="nfl-qb-name">
                    <span className="nfl-elo-swatch" style={{ background: team?.color ?? 'var(--border)' }} />
                    {fullName(t.team)}
                  </td>
                  <td className="nfl-elo-div">
                    {team ? `${team.conference} ${team.division}` : '—'}
                  </td>
                  <td className="num nfl-elo-value">{t.elo.toFixed(0)}</td>
                  <td className="num">{t.eloPreseason.toFixed(0)}</td>
                  <td className={`num ${change > 0 ? 'up' : change < 0 ? 'down' : 'flat'}`}>
                    {change > 0 ? '+' : ''}{change}
                  </td>
                  <td className="num">{record}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ── quarterback table ────────────────────────────────────────────────────────

function QbTable({ quarterbacks }: { quarterbacks: QbRating[] }) {
  return (
    <div className="nfl-qb-wrap">
      <p className="nfl-qb-intro">
        Every quarterback gets a rolling rating built from 538&apos;s <strong>VALUE</strong> —
        a regression of ESPN&apos;s Total QBR yards-above-replacement onto box score numbers,
        adjusted for the defense faced and updated 10% per start. <strong>vs League</strong> is
        what a passer is worth against an average starter. <strong>vs Team</strong> is what
        actually moves a line: the gap between him and his own team&apos;s recent quarterback
        level, which is why the adjustment fires on an injury and stays quiet otherwise.
      </p>
      <p className="nfl-qb-intro">
        A <strong>vs Team of 0</strong> is a result, not a gap in the data. A passer who has
        taken every snap for one team has his rating and that team&apos;s baseline updated by
        the same number after every game, so the two converge — about 90% of any starting gap
        is gone within 20 starts. Reading it plainly: this team&apos;s expected quarterback is
        exactly this man, so there is nothing to adjust for.
      </p>
      <div className="nfl-table-scroll">
        <table className="nfl-qb-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Quarterback</th>
              <th>Team</th>
              <th className="num">Rating</th>
              <th className="num">vs League</th>
              <th className="num">vs Team</th>
              <th className="num">Starts</th>
              <th className="num">Last</th>
            </tr>
          </thead>
          <tbody>
            {quarterbacks.map((q) => {
              const team = resolveTeam(q.team);
              return (
                <tr key={q.playerId}>
                  <td className="nfl-qb-rank">{q.rank}</td>
                  <td className="nfl-qb-name">{q.name}</td>
                  <td>
                    <span className="nfl-qb-team" style={{ borderColor: team?.color ?? 'var(--border)' }}>
                      {q.team}
                    </span>
                  </td>
                  <td className="num">{q.rating.toFixed(1)}</td>
                  <td className={`num ${q.eloVsAverage > 0 ? 'up' : q.eloVsAverage < 0 ? 'down' : 'flat'}`}>
                    {q.eloVsAverage > 0 ? '+' : ''}{q.eloVsAverage}
                  </td>
                  <td className={`num ${q.eloVsTeam > 0 ? 'up' : q.eloVsTeam < 0 ? 'down' : 'flat'}`}>
                    {q.eloVsTeam > 0 ? '+' : ''}{q.eloVsTeam}
                  </td>
                  <td className="num">{q.starts}</td>
                  <td className="num">{q.lastValue === null ? '—' : q.lastValue.toFixed(1)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      {quarterbacks.length === 0 && <div className="nfl-empty">No quarterback ratings yet.</div>}
    </div>
  );
}

// ── methodology + attribution ────────────────────────────────────────────────

function ModelNotes({ data }: { data: EloSeason }) {
  const generated = new Date(data.generatedAt);
  return (
    <section className="nfl-notes">
      <h2>How it works</h2>
      <p>
        Each team holds a single rating around a league mean of 1505. The difference between two
        ratings sets the win probability on a logistic curve where 400 points is about 10-to-1.
        After a game, ratings move by <code>K &times; (result &minus; expected)</code>, scaled by a
        margin-of-victory multiplier that grows with the log of the final margin and is damped by
        the winner&apos;s pre-game edge — without that damping, favourites who cover would ratchet
        upward forever. Between seasons every team reverts a third of the way to the mean.
      </p>
      <p>
        Quarterbacks are handled as a <em>differential</em>. Team rating already contains the
        contribution of whoever has been playing, so adding a passer&apos;s full value would
        double-count him. Only his gap from his team&apos;s recent quarterback level moves the
        line, at 3.5 Elo points per point of VALUE.
      </p>
      <p>
        The constants were re-fit rather than copied. Home field is worth <strong>32</strong> points
        here, not the 65 that 538 published: home teams won 57.3% of games in 2005&ndash;2014 but
        only 54.5% in 2021&ndash;2025, and the crowdless 2020 season came in at 50.4%. Grid-searched
        on {data.calibration.evaluatedGames.toLocaleString()} regular season games from 2015 on,
        this version scores <strong>{data.calibration.logLoss}</strong> log loss and{' '}
        <strong>{data.calibration.brierScore}</strong> Brier against{' '}
        {data.calibration.baselineLogLoss} and {data.calibration.baselineBrierScore} for 538&apos;s
        published defaults.
      </p>

      <h2>Data and attribution</h2>
      <p>
        Schedules, results, box scores and depth charts come from{' '}
        <a href="https://github.com/nflverse" target="_blank" rel="noopener noreferrer">nflverse</a>,
        used under{' '}
        <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
          CC BY 4.0
        </a>. The Elo method follows{' '}
        <a href="https://github.com/fivethirtyeight/nfl-elo-game" target="_blank" rel="noopener noreferrer">
          FiveThirtyEight&apos;s published implementation
        </a>. Live scores come from ESPN&apos;s public scoreboard and are fetched by your browser.
      </p>
      <p className="nfl-disclaimer">
        Not affiliated with, endorsed by, or sponsored by the National Football League or any of its
        teams. Names are used only to identify the teams whose games are described; no league or
        team logos, wordmarks or photography appear here. Ratings are published for informational and
        entertainment purposes — they are not betting advice.
      </p>
      <p className="nfl-generated">
        Ratings generated {generated.toLocaleString()} &middot; season {data.season}
        {data.throughWeek > 0 ? `, through week ${data.throughWeek}` : ', pre-season'}
      </p>
    </section>
  );
}

// ── styles ───────────────────────────────────────────────────────────────────

const NFL_CSS = `
.nfl-root{margin-bottom:4rem}
.nfl-loading,.nfl-empty,.nfl-error{padding:2rem;text-align:center;color:var(--text-muted);background:var(--surface);border:1px solid var(--border-subtle);border-radius:var(--radius-md)}
.nfl-error{color:var(--accent-warm)}

/* filter chips */
.nfl-filter{display:flex;flex-wrap:wrap;gap:0.35rem;margin-bottom:1.75rem}
.nfl-chip{--chip-color:var(--accent-primary);display:flex;flex-direction:column;align-items:center;gap:1px;min-width:3.1rem;padding:0.36rem 0.5rem;background:var(--surface-raised);border:1px solid var(--border-subtle);border-bottom:2px solid var(--chip-color);border-radius:var(--radius-sm);font-family:inherit;font-size:0.72rem;font-weight:700;letter-spacing:0.03em;color:var(--text-primary);cursor:pointer;transition:all var(--transition-fast)}
.nfl-chip:hover{background:var(--surface-hover);transform:translateY(-1px)}
.nfl-chip.active{background:var(--chip-color);color:#fff;border-color:transparent}
.nfl-chip.active .nfl-chip-elo{color:rgba(255,255,255,0.85)}
.nfl-chip-elo{font-size:0.62rem;font-weight:600;color:var(--text-muted);letter-spacing:0}
.nfl-chip-all,.nfl-chip-qb,.nfl-chip-ratings{--chip-color:var(--accent-secondary);justify-content:center;padding-inline:0.85rem}
.nfl-chip-qb{--chip-color:var(--accent-warm)}
.nfl-chip-ratings{--chip-color:var(--accent-primary)}

/* layout: sticky week rail + games */
.nfl-layout{display:grid;grid-template-columns:150px minmax(0,1fr);gap:1.75rem;align-items:start}
.nfl-weeks{position:sticky;top:calc(var(--nav-height) + 1rem);max-height:calc(100vh - var(--nav-height) - 3rem);overflow-y:auto}
.nfl-weeks-title{font-size:0.68rem;font-weight:800;letter-spacing:0.12em;text-transform:uppercase;color:var(--text-muted);margin-bottom:0.5rem}
.nfl-weeks-list{display:flex;flex-direction:column;gap:2px}
.nfl-week-link{display:flex;align-items:center;justify-content:space-between;gap:0.5rem;width:100%;padding:0.4rem 0.6rem;background:transparent;border:none;border-left:2px solid var(--border-subtle);border-radius:0 var(--radius-sm) var(--radius-sm) 0;font-family:inherit;font-size:0.8rem;font-weight:600;color:var(--text-secondary);text-align:left;cursor:pointer;transition:all var(--transition-fast)}
.nfl-week-link:hover{background:var(--surface-hover);color:var(--text-primary)}
.nfl-week-link.active{background:var(--surface);border-left-color:var(--accent-primary);border-left-width:3px;color:var(--accent-primary);font-weight:800;padding-left:0.7rem}
.nfl-week-link.now{font-weight:800}
.nfl-week-link.now::after{content:'';width:5px;height:5px;border-radius:50%;background:var(--accent-secondary);flex:none}
.nfl-week-count{font-size:0.68rem;color:var(--text-muted);font-weight:600}
.nfl-week-link.active .nfl-week-count{color:var(--accent-primary)}
.nfl-weeks-note{margin-top:0.75rem;font-size:0.7rem;line-height:1.5;color:var(--text-muted)}

.nfl-week-section{margin-bottom:2.25rem;scroll-margin-top:90px}
.nfl-week-heading{display:flex;align-items:center;gap:0.6rem;font-size:1rem;font-weight:800;letter-spacing:0.02em;margin:0 0 0.75rem;color:var(--text-primary)}
.nfl-now-badge{padding:0.14rem 0.45rem;background:var(--accent-secondary);color:#fff;border-radius:999px;font-size:0.62rem;font-weight:700;letter-spacing:0.05em;text-transform:uppercase}

/* game card */
.nfl-game{background:var(--surface-raised);border:1px solid var(--border-subtle);border-radius:var(--radius-md);padding:0.7rem 0.85rem;margin-bottom:0.6rem;transition:border-color var(--transition-fast)}
.nfl-game:hover{border-color:var(--border)}
.nfl-game-top{display:flex;justify-content:space-between;align-items:baseline;gap:1rem;margin-bottom:0.5rem}
.nfl-status{font-size:0.72rem;font-weight:700;color:var(--text-secondary)}
.nfl-status-live{color:var(--accent-warm)}
.nfl-status-live::before{content:'';display:inline-block;width:6px;height:6px;margin-right:5px;border-radius:50%;background:var(--accent-warm);animation:nfl-pulse 1.6s ease-in-out infinite}
.nfl-status-final{color:var(--text-muted)}
@keyframes nfl-pulse{0%,100%{opacity:1}50%{opacity:0.25}}
.nfl-venue{font-size:0.68rem;color:var(--text-muted);text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}

.nfl-side{display:grid;grid-template-columns:3px 4.6rem minmax(0,1fr) 2rem 2.9rem;align-items:center;gap:0.55rem;padding:0.24rem 0}
.nfl-side.loser{opacity:0.5}
.nfl-side-bar{height:1.15rem;border-radius:2px}
.nfl-side-name{display:flex;flex-direction:column;line-height:1.15}
.nfl-side-abbr{font-size:0.86rem;font-weight:800;letter-spacing:0.02em}
.nfl-side-full{font-size:0.64rem;color:var(--text-muted)}
.nfl-side-qb{font-size:0.75rem;color:var(--text-secondary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.nfl-side-qb em{font-style:normal;font-weight:700;font-size:0.66rem;margin-left:0.35rem}
.nfl-side-qb em.up,td.num.up{color:var(--accent-secondary)}
.nfl-side-qb em.down,td.num.down{color:var(--accent-warm)}
.nfl-side-qb em.flat,td.num.flat{color:var(--text-muted)}
.nfl-side-score{font-size:1.02rem;font-weight:800;text-align:right;font-variant-numeric:tabular-nums}
.nfl-side.winner .nfl-side-score{color:var(--accent-secondary)}
.nfl-side-prob{font-size:0.82rem;font-weight:700;text-align:right;color:var(--text-secondary);font-variant-numeric:tabular-nums}

.nfl-bar{display:flex;height:4px;border-radius:999px;overflow:hidden;margin:0.45rem 0 0.4rem;background:var(--surface)}
.nfl-bar-away,.nfl-bar-home{display:block;height:100%}
.nfl-bar-away{opacity:0.55}

.nfl-game-foot{display:flex;justify-content:space-between;gap:1rem;font-size:0.68rem;color:var(--text-muted)}
.nfl-game-foot strong{color:var(--text-secondary)}

/* quarterback table */
.nfl-qb-wrap{margin-bottom:2rem}
.nfl-qb-intro{font-size:0.85rem;line-height:1.7;color:var(--text-secondary);margin-bottom:1.1rem;max-width:70ch}
.nfl-table-scroll{overflow-x:auto;border:1px solid var(--border-subtle);border-radius:var(--radius-md)}
.nfl-qb-table{width:100%;border-collapse:collapse;font-size:0.84rem;min-width:640px}
.nfl-qb-table th{position:sticky;top:0;background:var(--surface);padding:0.6rem 0.7rem;text-align:left;font-size:0.68rem;font-weight:800;letter-spacing:0.06em;text-transform:uppercase;color:var(--text-muted);border-bottom:1px solid var(--border-subtle)}
.nfl-qb-table td{padding:0.5rem 0.7rem;border-bottom:1px solid var(--border-subtle)}
.nfl-qb-table tr:last-child td{border-bottom:none}
.nfl-qb-table tbody tr:hover{background:var(--surface-hover)}
.nfl-qb-table .num{text-align:right;font-variant-numeric:tabular-nums}
.nfl-more{display:block;width:100%;padding:0.7rem 1rem;margin-bottom:1rem;background:var(--surface);border:1px dashed var(--border);border-radius:var(--radius-md);font-family:inherit;font-size:0.78rem;font-weight:600;color:var(--text-secondary);cursor:pointer;transition:all var(--transition-fast)}
.nfl-more:hover{border-color:var(--accent-primary);color:var(--accent-primary);background:var(--surface-hover)}
.nfl-sentinel{min-height:1px}

.nfl-elo-swatch{display:inline-block;width:3px;height:0.85rem;border-radius:2px;margin-right:0.5rem;vertical-align:-1px}
.nfl-elo-div{font-size:0.74rem;color:var(--text-muted);white-space:nowrap}
.nfl-elo-value{font-weight:800}
.nfl-qb-rank{color:var(--text-muted);font-weight:700;width:2.5rem}
.nfl-qb-name{font-weight:700;width:100%}
.nfl-qb-table th.num,.nfl-qb-table td.num{white-space:nowrap;width:1%}
.nfl-qb-team{display:inline-block;padding:0.1rem 0.4rem;border:1px solid;border-radius:var(--radius-sm);font-size:0.7rem;font-weight:800;letter-spacing:0.03em}

/* notes */
.nfl-notes{margin-top:2.5rem;padding-top:1.75rem;border-top:1px solid var(--border-subtle)}
.nfl-notes h2{font-size:0.95rem;font-weight:800;letter-spacing:0.02em;margin:1.5rem 0 0.6rem;color:var(--text-primary)}
.nfl-notes h2:first-child{margin-top:0}
.nfl-notes p{font-size:0.82rem;line-height:1.75;color:var(--text-secondary);max-width:75ch;margin-bottom:0.8rem}
.nfl-notes code{font-size:0.78rem;background:var(--surface);padding:0.1rem 0.3rem;border-radius:4px}
.nfl-notes a{color:var(--accent-secondary)}
.nfl-disclaimer{font-size:0.74rem !important;color:var(--text-muted) !important}
.nfl-generated{font-size:0.72rem !important;color:var(--text-muted) !important}

@media (max-width:860px){
  .nfl-layout{grid-template-columns:1fr;gap:0}
  /* The rail becomes a strip that sticks under the nav, and each week's name
     rides along beneath it as a section header — so there is always a week
     labelled at the top of the screen. */
  /* The week name is the sticky element on mobile — it rides under the nav and
     hands off to the next week as you scroll, so there is always a week
     labelled at the top. The jump strip scrolls away with the page rather than
     stacking a second sticky bar onto a 390px screen. */
  .nfl-weeks{position:static;max-height:none;margin-bottom:0.75rem;padding-bottom:0.25rem;border-bottom:1px solid var(--border-subtle)}
  .nfl-weeks-title{display:none}
  .nfl-weeks-list{flex-direction:row;overflow-x:auto;gap:0.3rem;padding-bottom:0.5rem;scrollbar-width:none}
  .nfl-weeks-list::-webkit-scrollbar{display:none}
  .nfl-week-link{flex:none;width:auto;gap:0.4rem;border-left:none;border-bottom:2px solid var(--border-subtle);border-radius:var(--radius-sm);padding:0.35rem 0.6rem}
  .nfl-week-link.active{border-bottom-color:var(--accent-primary);padding:0.35rem 0.6rem}
  .nfl-weeks-note{display:none}
  .nfl-week-section{margin-bottom:1.5rem;scroll-margin-top:120px}
  .nfl-week-heading{position:sticky;top:var(--nav-height);z-index:5;margin:0 -1rem 0.6rem;padding:0.55rem 1rem;background:var(--background);border-bottom:1px solid var(--border-subtle)}
  .nfl-side{grid-template-columns:3px 3.4rem minmax(0,1fr) 1.8rem 2.6rem;gap:0.45rem}
  .nfl-side-full,.nfl-venue{display:none}
}
`;
